config/routes.rb
Csshacks::Application.routes.draw do
  devise_for :users 
  resources :hacks

  root :to => "hacks#index"
  
  get "users/:id" => "users#show"

  

end

app/models/hack.rb
class Hack < ActiveRecord::Base
  attr_accessible :id, :title, :css, :html, :html_display
  validates_presence_of :title, :css, :html

  belongs_to :user
  
  def format_html
    html.gsub("<","&lt;").gsub(">","&gt;")
  end

  def nest_css
    ".style-container {" + css + "}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me, :hacks

  has_many :hacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :new_hack 

  
  def new_hack
    @hack = Hack.new
  end

end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
  # GET /hacks
  # GET /hacks.json
  def index
    @hacks = Hack.all
    @hack = Hack.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hacks }
    end
  end

  # GET /hacks/1
  # GET /hacks/1.json
  def show
    @hack = Hack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hack }
    end
  end

  # GET /hacks/new
  # GET /hacks/new.json
  def new
    @hack = Hack.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hack }
    end
  end

  # GET /hacks/1/edit
  def edit
    @hack = Hack.find(params[:id])
  end

  # POST /hacks
  # POST /hacks.json
  def create
    @hack = Hack.new(params[:hack])
    @hack.html_display = @hack.format_html
    # @hack.css = @hack.nest_css
    @hack.user_id = current_user.id

    respond_to do |format|
      if @hack.save
        format.html { redirect_to @hack, notice: 'Hack was successfully created.' }
        format.json { render json: @hack, status: :created, location: @hack }
      else
        format.html { render action: "new" }
        format.json { render json: @hack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hacks/1
  # PUT /hacks/1.json
  def update
    @hack = Hack.find(params[:id])

    respond_to do |format|
      if @hack.update_attributes(params[:hack])
        format.html { redirect_to @hack, notice: 'Hack was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hacks/1
  # DELETE /hacks/1.json
  def destroy
    @hack = Hack.find(params[:id])
    @hack.destroy

    respond_to do |format|
      format.html { redirect_to hacks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @name = @user.first_name

    respond_to do |format|
      format.html { render "users/sessions/show"}
      format.json { render json: @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # before_filter :configure_permitted_parameters, if: :devise_controller?
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end


end

app/helpers/hacks_helper.rb
module HacksHelper
end

app/views/hacks/_form.html.erb
      <%= form_for(@hack) do |f| %>
        <% if @hack.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@hack.errors.count, "error") %> prohibited this hack from being saved:</h2>

            <ul>
            <% @hack.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="modal-body">
          <div class="field">
            <%= f.label :title %><br />
            <%= f.text_field :title %>
          </div>
          <div class="field">
            <%= f.label :css %><br />
            <%= f.text_area :css %>
          </div>
          <div class="field">
            <%= f.label :html %><br />
            <%= f.text_area :html %>
          </div>

          <div class="actions">
            <%= f.submit %>
          </div>
        </div>
      <% end %>

app/views/hacks/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Enter the code for your hack</h4>
      </div>
      
      <%= render 'hacks/form' %>
      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/hacks/_slidecontent.html.erb
<div class="container">


  <!-- TITLE -->
  <div class="col-md-12"> 
    <h2> <%= hack.title.upcase %></h2>
  </div>


  <!-- Nav tabs -->

  <ul class="nav nav-tabs hack-options">
    <div class="btn-group center-block">
      <button href=".hack" type="button" data-toggle="tab" class="btn btn-default tab">Hack</button>
      <button href=".code" type="button" data-toggle="tab" class="btn btn-default tab">Code</button>
    </div>

    <ul class="nav-tabs navbar-right">
      <li><a> 
          <% if hack.user %>
            <%= "Created by: #{hack.user.first_name}" %>
          <% end %>
        </a>
      </li>
      <li>
        <a> <%= link_to "Edit", edit_hack_path(hack) %></a>
      </li>
    </ul>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <!-- RESULTS -->
    <div class="tab-pane active hack">
      <!-- HTML FOR ENTRY HERE -->
      <div class="style-container">
        <%= hack.html.html_safe %>
      </div>
      <!-- CSS FOR ENTRY HERE -->
      <style type="text/css">
          <%= hack.css %>
      </style>
       
    </div>
    
    <!-- CODE  -->
    <div class="tab-pane code">
      <div class="col-md-6"> 
        <h4> CSS </h4>
        <pre class="prettyprint"> 
          <%= hack.css %>
        </pre>
      </div>
      <div class="col-md-6"> 
        <h4> HTML </h4>
        <pre class="prettyprint"> 
          <%= hack.html_display.html_safe %>
        </pre>
      </div>
    </div>
  </div>
</div>

app/views/hacks/_welcome.html.erb
<div class="welcome">
  <div class="container">
    <%= image_tag "images/heading.png", :class=>"center block heading" %>
    <div class="center welcome-btn-container block">
      <%= link_to "View Gallery", "#css-carousel", :class => "btn btn-primary btn-margin btn-lg" %>
      <%= link_to "Sign Up",  new_user_registration_path, :class => "btn btn-primary btn-margin btn-lg" %>
    </div>
  </div>
</div>

app/views/hacks/edit.html.erb
<div class="container">
  <h1>Editing hack</h1>

  <%= render 'hacks/form' %>

  <%= link_to 'Show', @hack %> |
  <%= link_to 'Back', hacks_path %> | 
  <%= link_to 'Destroy', @hack, confirm: 'Are you sure?', method: :delete %>


</div>

app/views/hacks/index.html.erb
<% unless user_signed_in? %>
  <%= render 'welcome' %>
<% end %>

<div id="css-carousel" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#css-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#css-carousel" data-slide-to="1"></li>
    <li data-target="#css-carousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">

    <div class="item active">
      <%= render 'slidecontent', hack: @hacks.first %>
    </div>

    <% @hacks.drop(1).each do |hack| %>
      <div class="item" id="<%=hack.id%>">
        <%= render 'slidecontent', hack: hack %>
      <!-- <div class="carousel-caption"></div> -->
      </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#css-carousel" data-slide="prev">
    <!-- <span class="glyphicon glyphicon-chevron-left"></span> -->
    <%= image_tag "images/arrow-left.png", :class=>"arrow"%>
  </a>
  <a class="right carousel-control" href="#css-carousel" data-slide="next">
    <!-- <span class="glyphicon glyphicon-chevron-right"></span> -->
    <%= image_tag "images/arrow-right.png", :class=>"arrow"%>
  </a>
</div>

    <%#= link_to 'Show', hack %>
    <%#= link_to 'Edit', edit_hack_path(hack) %>
    <%#= button_to 'Destroy', hack, confirm: 'Are you sure?', method: :delete %>



<%#= link_to 'New Hack', new_hack_path %>

app/views/hacks/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Title:</b>
    <%= @hack.title %>
  </p>

  <p>
    <b>Css:</b>
    <%= @hack.css %>
  </p>

  <p>
    <b>Html:</b>
    <%= @hack.html %>
  </p>

  <p>
    <b>Html display:</b>
    <%= @hack.html_display %>
  </p>


  <%= link_to 'Edit', edit_hack_path(@hack) %> |
  <%= link_to 'Back', hacks_path %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <ul class="navbar-nav navbar-left footer">
    <li>&copy; CSS Hacks, Inc. </li>
    <li><a href="#">Privacy </a></li>
    <li><a href="#">Terms </a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li>Back to top</li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar" >
  <ul class="nav navbar-nav navbar-left nav-main">
    <li><a href="/" class="brand ">CSS HACKS</a></li>
  </ul>
  
  <!-- Button trigger modal -->
  <ul class="nav navbar-nav navbar-right nav-main">
      
      <li><a href="/#css-carousel" class="active">Gallery</a></li>
      <li><a href="#">Categories</a></li>
      <li><a href="#">About</a></li>
      
    <% if user_signed_in? %>
      <li>
        <%= link_to "New Hack", "#", "data-toggle" => "modal", "data-target"=>"#myModal" %>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
          <%= "Hi, #{current_user.first_name}" %>
           <b class="caret"></b>
        </a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <li><a href="/users/<%= current_user.id%>">My Hacks</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li class="divider"></li>
          <li><%= button_to "Logout", destroy_user_session_path, method: :delete %> </li>
        </ul>
      </li>

    <% else %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
          Sign in <b class="caret"></b>
        </a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          
          <div class="tab-content">
            <div class="tab-pane active" id="signin">
              <%= render 'users/sessions/new' %>
            </div>
            <div class="tab-pane" id="signup">
              <%= render 'users/registrations/new' %>
              
            </div>
          </div>

          
          
        </ul>
      </li>

    <% end %>
  </ul>


</div>
   
<%= render 'hacks/modal' %>

<!-- SCRIPTS -->
<script src="javascripts/bootstrap.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSS Hacks</title>
    <!-- FONTS -->
    <link href='http://fonts.googleapis.com/css?family=Nixie+One|Parisienne|Gilda+Display|Oleo+Script+Swash+Caps|Simonetta|PT+Mono|Josefin+Sans|Londrina+Outline|Alegreya+Sans|Open+Sans+Condensed:300|Open+Sans|Varela+Round|Amatic+SC|Text+Me+One' rel='stylesheet' type='text/css'>
    
    <!-- STYLESHEETS -->
    <!-- PRETTYPRINT For Syntax Highlighting -->
    <link href="http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.css" type="text/css" rel="stylesheet"/>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <!-- JS -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <%#= javascript_include_tag "bootstrap.min" %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.js"></script>
    <body onload="prettyPrint()">
    
    
    
  </body>

</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>